import { ProgramProfile } from '../types/programProfile.ts';

export const MEESHO_PROGRAM_PROFILE: ProgramProfile = {
  id: 'meesho-hackerone',
  handle: 'meesho',
  name: 'Meesho Bug Bounty Program',
  platform: 'HackerOne',
  policyUrl: 'https://hackerone.com/meesho',
  rewardCeiling: '$10,000',
  status: 'ACTIVE',
  description:
    'Meesho HackerOne authorized bug bounty scope strictly covering explicitly enumerated web properties, API gateways, logistics endpoints, and verified mobile application packages. Broad wildcards are explicitly ineligible and must not grant authorization.',
  inScopeAssets: [
    {
      id: 'asset-meesho-valmo-www',
      targetPattern: 'www.valmo.in',
      assetType: 'DOMAIN',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Valmo Logistics web portal',
    },
    {
      id: 'asset-meesho-www',
      targetPattern: 'www.meesho.com',
      assetType: 'DOMAIN',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Meesho primary marketplace web platform (www)',
    },
    {
      id: 'asset-meesho-supplier',
      targetPattern: 'supplier.meesho.com',
      assetType: 'DOMAIN',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Meesho Supplier Hub & seller administration dashboard',
    },
    {
      id: 'asset-meesho-prod-api',
      targetPattern: 'prod.meeshoapi.com',
      assetType: 'API_ENDPOINT',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Production core Meesho API gateway',
    },
    {
      id: 'asset-meesho-valmo-app-android',
      targetPattern: 'com.valmo.valmo',
      assetType: 'MOBILE_APP_ANDROID',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Valmo Android Logistics Application (Google Play package: com.valmo.valmo)',
    },
    {
      id: 'asset-meesho-supply-app-android',
      targetPattern: 'com.meesho.supply',
      assetType: 'MOBILE_APP_ANDROID',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Meesho Android Consumer & Reseller Application (Google Play package: com.meesho.supply)',
    },
    {
      id: 'asset-meesho-affiliate',
      targetPattern: 'affiliate.meesho.com',
      assetType: 'DOMAIN',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Meesho Affiliate partner portal',
    },
    {
      id: 'asset-meesho-admin-supply',
      targetPattern: 'admin.meeshosupply.com',
      assetType: 'DOMAIN',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Meesho Supply administration portal',
    },
    {
      id: 'asset-meesho-ios-app-id',
      targetPattern: '1457958492',
      assetType: 'MOBILE_APP_IOS',
      bountyEligible: true,
      maxSeverity: 'CRITICAL',
      description: 'Meesho iOS Application (Apple App Store ID: 1457958492)',
    },
    {
      id: 'asset-meesho-superstore',
      targetPattern: 'superstoreapp.meesho.com',
      assetType: 'DOMAIN',
      bountyEligible: true,
      maxSeverity: 'HIGH',
      description: 'Meesho Superstore mobile/web ordering platform (Operational constraints strictly apply)',
      operationalConstraints: ['op-nagpur-pin', 'op-cancel-window'],
    },
    {
      id: 'asset-meesho-io',
      targetPattern: 'meesho.io',
      assetType: 'DOMAIN',
      bountyEligible: true,
      maxSeverity: 'LOW',
      description: 'Meesho engineering & developer portal root',
    },
    {
      id: 'asset-meesho-investor',
      targetPattern: 'investor.meesho.com',
      assetType: 'DOMAIN',
      bountyEligible: true,
      maxSeverity: 'LOW',
      description: 'Meesho Investor Relations portal',
    },
  ],
  outOfScopeAssets: [
    // Explicitly Ineligible Named Assets
    {
      id: 'oos-meesho-warehouse',
      targetPattern: 'warehouse.meesho.com',
      assetType: 'DOMAIN',
      reason: 'Explicitly listed as ineligible in program scope',
    },
    {
      id: 'oos-meesho-rider-app',
      targetPattern: 'Rider App',
      assetType: 'OTHER',
      reason: 'Explicitly listed as ineligible in program scope',
    },
    {
      id: 'oos-meesho-other-asset',
      targetPattern: 'Other Asset',
      assetType: 'OTHER',
      reason: 'Explicitly listed as ineligible in program scope',
    },
    {
      id: 'oos-meesho-valmo-staging',
      targetPattern: 'log10-web-staging.valmo.in',
      assetType: 'DOMAIN',
      reason: 'Valmo pre-production / staging environment (ineligible)',
    },
    {
      id: 'oos-meesho-grocery-supplier',
      targetPattern: 'grocery-supplier.meesho.com',
      assetType: 'DOMAIN',
      reason: 'Explicitly listed as ineligible in program scope',
    },
    {
      id: 'oos-meesho-farmiso-supply',
      targetPattern: 'farmiso.meeshosupply.com',
      assetType: 'DOMAIN',
      reason: 'Explicitly listed as ineligible in program scope',
    },
    {
      id: 'oos-meesho-superset',
      targetPattern: 'di-prd-superset.meesho.com',
      assetType: 'DOMAIN',
      reason: 'Internal analytics / Superset instance (ineligible)',
    },
    {
      id: 'oos-meesho-valmo-console',
      targetPattern: 'console.valmo.in',
      assetType: 'DOMAIN',
      reason: 'Valmo internal administrative console (ineligible)',
    },
    {
      id: 'oos-meesho-valmo-ops-android',
      targetPattern: 'com.valmo.ops',
      assetType: 'MOBILE_APP_ANDROID',
      reason: 'Internal logistics operations package (ineligible)',
    },
    {
      id: 'oos-meesho-valmo-atlas',
      targetPattern: 'atlas.valmo.in',
      assetType: 'DOMAIN',
      reason: 'Valmo internal tracking & routing engine (ineligible)',
    },
    {
      id: 'oos-meesho-agency',
      targetPattern: 'agency.meesho.com',
      assetType: 'DOMAIN',
      reason: 'Explicitly listed as ineligible in program scope',
    },
    {
      id: 'oos-meesho-affiliate-c',
      targetPattern: 'affiliate-c.meesho.com',
      assetType: 'DOMAIN',
      reason: 'Explicitly listed as ineligible in program scope',
    },
    {
      id: 'oos-meesho-admin-io',
      targetPattern: 'admin.meesho.io',
      assetType: 'DOMAIN',
      reason: 'Internal developer admin service (ineligible)',
    },

    // Explicitly Ineligible Wildcards (Must NEVER grant ALLOW)
    {
      id: 'oos-meesho-wildcard-valmo',
      targetPattern: '*.valmo.in',
      assetType: 'WILDCARD',
      reason: 'Wildcard domain is explicitly listed as INELIGIBLE by program rules. Only explicit in-scope assets are acceptable.',
      isWildcardIneligible: true,
    },
    {
      id: 'oos-meesho-wildcard-meeshosupply',
      targetPattern: '*.meeshosupply.com',
      assetType: 'WILDCARD',
      reason: 'Wildcard domain is explicitly listed as INELIGIBLE by program rules. Only explicit in-scope assets are acceptable.',
      isWildcardIneligible: true,
    },
    {
      id: 'oos-meesho-wildcard-meeshogcp',
      targetPattern: '*.meeshogcp.in',
      assetType: 'WILDCARD',
      reason: 'Wildcard domain is explicitly listed as INELIGIBLE by program rules.',
      isWildcardIneligible: true,
    },
    {
      id: 'oos-meesho-wildcard-meeshoapi',
      targetPattern: '*.meeshoapi.com',
      assetType: 'WILDCARD',
      reason: 'Wildcard domain is explicitly listed as INELIGIBLE by program rules. Only explicit in-scope endpoints like prod.meeshoapi.com are acceptable.',
      isWildcardIneligible: true,
    },
    {
      id: 'oos-meesho-wildcard-meeshoaiservices',
      targetPattern: '*.meeshoaiservices.ai',
      assetType: 'WILDCARD',
      reason: 'Wildcard domain is explicitly listed as INELIGIBLE by program rules.',
      isWildcardIneligible: true,
    },
    {
      id: 'oos-meesho-wildcard-meesho',
      targetPattern: '*.meesho.com',
      assetType: 'WILDCARD',
      reason: 'Wildcard domain is explicitly listed as INELIGIBLE by program rules. Only specific named subdomains in the in-scope asset list are authorized.',
      isWildcardIneligible: true,
    },
  ],
  operationalConstraints: [
    {
      id: 'op-nagpur-pin',
      targetPattern: 'superstoreapp.meesho.com',
      constraintType: 'LOCATION_RESTRICTION',
      name: 'Superstore PIN Code Restriction (Nagpur 440002)',
      description: 'Testing on Superstore must exclusively use Nagpur PIN code 440002.',
      mandatoryWarning:
        '[OPERATIONAL CONSTRAINT] Superstore testing is STRICTLY restricted to PIN code 440002 (Nagpur). Do not use real user PIN codes or addresses.',
    },
    {
      id: 'op-cancel-window',
      targetPattern: 'superstoreapp.meesho.com',
      constraintType: 'CANCELLATION_WINDOW',
      name: 'Superstore Order Cancellation Window Constraint',
      description: 'All orders placed during testing on Superstore must be cancelled within 30 minutes of creation.',
      mandatoryWarning:
        '[OPERATIONAL CONSTRAINT] Any test order placed on Superstore MUST be cancelled within 30 minutes of creation to avoid real fulfillment/dispatch.',
    },
    {
      id: 'op-rate-limit-general-policy',
      targetPattern: '*',
      constraintType: 'RATE_LIMIT_POLICY',
      name: 'Program Rate Limit & Traffic Caution Policy',
      description:
        'Program-specific rate limit is NOT SPECIFIED. Hazardous, abusive, or high-volume automated traffic requires explicit authorization/review to prevent service disruption.',
      mandatoryWarning:
        '[OPERATIONAL CONSTRAINT] Program-specific numeric rate limit is NOT SPECIFIED. Keep testing volume gentle; hazardous or high-volume testing requires explicit authorization.',
    },
  ],
  rateLimitPolicy: {
    numericLimitSpecified: false,
    description:
      'Program-specific numeric rate limit is NOT SPECIFIED by Meesho policy. High-volume traffic or stress testing requires explicit authorization.',
  },
  findingEligibilityRules: [
    // Qualifying Core Vulnerabilities (When real security impact is demonstrated)
    {
      id: 'rule-bola-idor',
      vulnerabilityCategory: 'Broken Object Level Authorization (BOLA / IDOR)',
      cwe: 'CWE-639',
      classification: 'QUALIFYING',
      eligible: true,
      reason: 'BOLA/IDOR allowing unauthorized cross-tenant or cross-user data access is bounty eligible.',
      impactRequirement: 'Demonstrated unauthorized access to or modification of another user/tenant data.',
    },
    {
      id: 'rule-rce',
      vulnerabilityCategory: 'Remote Code Execution (RCE)',
      cwe: 'CWE-94',
      classification: 'QUALIFYING',
      eligible: true,
      reason: 'Remote code execution or command injection on any in-scope server is top-tier bounty eligible.',
      impactRequirement: 'Proof of command execution or arbitrary code interpretation.',
    },
    {
      id: 'rule-sqli',
      vulnerabilityCategory: 'SQL Injection (SQLi)',
      cwe: 'CWE-89',
      classification: 'QUALIFYING',
      eligible: true,
      reason: 'SQL injection allowing unauthorized database read/write is bounty eligible.',
      impactRequirement: 'Demonstrated SQL query manipulation.',
    },
    {
      id: 'rule-auth-bypass',
      vulnerabilityCategory: 'Authentication Bypass / Privilege Escalation',
      cwe: 'CWE-287',
      classification: 'QUALIFYING',
      eligible: true,
      reason: 'Flaws allowing account takeover or unauthorized administrative escalation are bounty eligible.',
      impactRequirement: 'Proof of session hijack, account takeover, or administrative elevation.',
    },
    {
      id: 'rule-ssrf',
      vulnerabilityCategory: 'Server-Side Request Forgery (SSRF)',
      cwe: 'CWE-918',
      classification: 'QUALIFYING',
      eligible: true,
      reason: 'Blind or non-blind SSRF accessing internal cloud metadata or internal services is bounty eligible.',
      impactRequirement: 'Demonstrated reach to internal metadata (e.g. 169.254.169.254) or intranet services.',
    },
    {
      id: 'rule-business-logic',
      vulnerabilityCategory: 'Business Logic Flaw / Payment Tampering',
      cwe: 'CWE-840',
      classification: 'QUALIFYING',
      eligible: true,
      reason: 'Logic flaws allowing price tampering, currency conversion bypass, or cart manipulation are bounty eligible.',
      impactRequirement: 'Proof of financial, quantity, or workflow state corruption.',
    },

    // Impact-Dependent Vulnerabilities (Eligible ONLY with demonstrated security impact)
    {
      id: 'rule-impact-xss',
      vulnerabilityCategory: 'Cross-Site Scripting (XSS)',
      cwe: 'CWE-79',
      classification: 'IMPACT_DEPENDENT',
      eligible: true,
      reason: 'XSS is eligible when demonstrated with realistic impact on other users; self-XSS without chaining is ineligible.',
      impactRequirement: 'Must execute in the context of another victim user (Stored/Reflected), not purely Self-XSS.',
    },
    {
      id: 'rule-impact-cors',
      vulnerabilityCategory: 'Cross-Origin Resource Sharing (CORS) Misconfiguration',
      cwe: 'CWE-942',
      classification: 'IMPACT_DEPENDENT',
      eligible: true,
      reason: 'CORS misconfiguration is eligible ONLY when sensitive user data or authentication tokens can be exfiltrated cross-origin.',
      impactRequirement: 'Requires proof of sensitive authenticated data retrieval via CORS.',
    },
    {
      id: 'rule-impact-open-redirect',
      vulnerabilityCategory: 'Open Redirect',
      cwe: 'CWE-601',
      classification: 'IMPACT_DEPENDENT',
      eligible: true,
      reason: 'Open redirect is eligible ONLY when leaking sensitive authorization tokens, OAuth credentials, or bypassing security boundaries.',
      impactRequirement: 'Requires demonstrated token leakage or security mechanism bypass.',
    },
    {
      id: 'rule-impact-rate-limit',
      vulnerabilityCategory: 'Rate Limiting / Account Takeover via Brute Force',
      cwe: 'CWE-799',
      classification: 'IMPACT_DEPENDENT',
      eligible: true,
      reason: 'Missing rate limiting is eligible ONLY where practical high-impact exploit (such as OTP brute force leading to ATO) is demonstrated.',
      impactRequirement: 'Proof of account takeover or direct financial fraud.',
    },

    // HackerOne Core Ineligible Findings / Standard Exclusions (Generally non-qualifying)
    {
      id: 'rule-ineligible-spf-dmarc',
      vulnerabilityCategory: 'Missing SPF/DKIM/DMARC Records',
      cwe: 'CWE-290',
      classification: 'HACKERONE_CORE_INELIGIBLE',
      eligible: false,
      reason:
        'Missing or loose SPF, DKIM, or DMARC DNS records without demonstrating actual fraudulent email inbox delivery to Meesho users are non-qualifying.',
    },
    {
      id: 'rule-ineligible-self-xss',
      vulnerabilityCategory: 'Self-XSS',
      cwe: 'CWE-79',
      classification: 'HACKERONE_CORE_INELIGIBLE',
      eligible: false,
      reason:
        'Self-Cross-Site Scripting where a researcher can only trigger Javascript within their own authenticated session without user interaction is non-qualifying.',
    },
    {
      id: 'rule-ineligible-banner-grabbing',
      vulnerabilityCategory: 'Banner Grabbing / Version Disclosure',
      cwe: 'CWE-200',
      classification: 'HACKERONE_CORE_INELIGIBLE',
      eligible: false,
      reason:
        'Server banners, tech stack disclosure, or software version enumeration without a working proof-of-concept exploit are non-qualifying.',
    },
    {
      id: 'rule-ineligible-missing-headers',
      vulnerabilityCategory: 'Missing Security Headers (CSP, HSTS, X-Frame-Options)',
      cwe: 'CWE-693',
      classification: 'HACKERONE_CORE_INELIGIBLE',
      eligible: false,
      reason:
        'Missing standard HTTP defensive headers without a direct exploitable vulnerability chain are non-qualifying.',
    },
    {
      id: 'rule-ineligible-clickjacking-low',
      vulnerabilityCategory: 'Clickjacking on Non-Sensitive Pages',
      cwe: 'CWE-1021',
      classification: 'HACKERONE_CORE_INELIGIBLE',
      eligible: false,
      reason:
        'Clickjacking / UI Redressing on static, promotional, or non-state-changing pages without proven sensitive impact is non-qualifying.',
    },
    {
      id: 'rule-ineligible-tabnabbing',
      vulnerabilityCategory: 'Tabnabbing / Reverse Tabnabbing',
      cwe: 'CWE-1022',
      classification: 'HACKERONE_CORE_INELIGIBLE',
      eligible: false,
      reason:
        'Target _blank links without rel="noopener noreferrer" without demonstrating credential harvesting are non-qualifying.',
    },
    {
      id: 'rule-ineligible-cookie-flags',
      vulnerabilityCategory: 'Missing Cookie Flags (SameSite, Secure, HttpOnly on non-sensitive cookies)',
      cwe: 'CWE-614',
      classification: 'HACKERONE_CORE_INELIGIBLE',
      eligible: false,
      reason:
        'Missing cookie flags on non-sensitive, tracking, or ephemeral cookies without demonstrated session compromise are non-qualifying.',
    },
    {
      id: 'rule-ineligible-tls-ciphers',
      vulnerabilityCategory: 'Weak TLS / SSL Ciphers without PoC',
      cwe: 'CWE-326',
      classification: 'HACKERONE_CORE_INELIGIBLE',
      eligible: false,
      reason:
        'Theoretical weak TLS ciphers or legacy SSL version support without active cryptographic break proof-of-concept are non-qualifying.',
    },
  ],
  hazardousOperationsRequireAuthorization: [
    'BRUTE_FORCE',
    'CREDENTIAL_STUFFING',
    'HIGH_VOLUME_AUTOMATED_SCAN',
    'RATE_LIMIT_STRESS_TEST',
    'AVAILABILITY_STRESS_TEST',
    'SENSITIVE_DATA_EXFILTRATION_TEST',
  ],
  prohibitedOperations: [
    'DOS',
    'DDOS',
    'VOLUMETRIC_DESTRUCTION',
    'SOCIAL_ENGINEERING',
    'PHISHING',
    'PHYSICAL_ATTACK',
    'DATA_DESTRUCTION',
  ],
  sensitiveOperations: [
    'SENSITIVE_DATA_EXFILTRATION_TEST',
    'PAYMENT_FLOW_VALIDATION',
    'ORDER_CANCELLATION_BYPASS_TEST',
    'PRIVILEGE_ESCALATION_TEST',
  ],
};
