import { CapabilityDefinition } from '../types.ts';

export const CAPABILITIES: CapabilityDefinition[] = [
  // ================= 1. HTTP / WEB SECURITY =================
  {
    id: 'cap-http-header-analysis',
    name: 'HTTP Security Header Analysis',
    description: 'Inspects HTTP response headers for missing security controls (HSTS, CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy).',
    category: 'HTTP / Web Security',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-693',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-csp-audit',
    name: 'Content Security Policy (CSP) Audit',
    description: 'Evaluates Content Security Policy directives for script injection bypasses, object-src restrictions, and unsafe-inline fallback rules.',
    category: 'HTTP / Web Security',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-1021',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-cors-policy-audit',
    name: 'CORS Policy Configuration Inspection',
    description: 'Analyzes Cross-Origin Resource Sharing headers for permissive wildcards, null origin reflection, and arbitrary origin trust with credentials.',
    category: 'HTTP / Web Security',
    owaspMapping: 'OWASP A01:2021-Broken Access Control',
    cweMapping: 'CWE-942',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'RECOMMENDED',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-http-methods-analysis',
    name: 'HTTP Method & Verb Analysis',
    description: 'Tests server response to OPTIONS, HEAD, and standard HTTP methods to observe allowed verbs and unexpected method overrides.',
    category: 'HTTP / Web Security',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-650',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-redirect-chain-analysis',
    name: 'HTTP Redirect Chain Analysis',
    description: 'Observes HTTP redirect status codes (301, 302, 307, 308), hop counts, destination protocols, and domain boundary transitions.',
    category: 'HTTP / Web Security',
    owaspMapping: 'OWASP A01:2021-Broken Access Control',
    cweMapping: 'CWE-601',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-cache-control-analysis',
    name: 'Cache-Control & Caching Preconditions Analysis',
    description: 'Inspects Cache-Control, Pragma, and Expires headers to evaluate client and intermediate proxy cacheability of sensitive resources.',
    category: 'HTTP / Web Security',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-525',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-mime-sniffing-analysis',
    name: 'MIME Sniffing & Content-Type Protection',
    description: 'Verifies X-Content-Type-Options nosniff enforcement and consistency between Content-Type header and observed response payload.',
    category: 'HTTP / Web Security',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-434',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-cross-origin-policies',
    name: 'Cross-Origin Isolation Policies Audit',
    description: 'Audits Cross-Origin-Opener-Policy (COOP), Cross-Origin-Embedder-Policy (COEP), and Cross-Origin-Resource-Policy (CORP) headers.',
    category: 'HTTP / Web Security',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-346',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 2. TLS / TRANSPORT SECURITY =================
  {
    id: 'cap-tls-ssl-audit',
    name: 'TLS/SSL Protocol & Cipher Suite Audit',
    description: 'Audits TLS protocol versions, cipher suite negotiation parameters, and encryption configurations on authorized targets.',
    category: 'TLS / Transport Security',
    owaspMapping: 'OWASP A02:2021-Cryptographic Failures',
    cweMapping: 'CWE-319',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-hsts-audit',
    name: 'Strict Transport Security (HSTS) Audit',
    description: 'Audits HTTP Strict Transport Security (HSTS) headers for max-age duration, includeSubDomains directive, and preload readiness.',
    category: 'TLS / Transport Security',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-319',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-cert-expiration-analysis',
    name: 'Certificate Validity & SAN Hostname Audit',
    description: 'Observes TLS certificate validFrom / validTo dates, subject common name, and Subject Alternative Name (SAN) hostname coverage.',
    category: 'TLS / Transport Security',
    owaspMapping: 'OWASP A02:2021-Cryptographic Failures',
    cweMapping: 'CWE-295',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-http-to-https-redirect',
    name: 'HTTP to HTTPS Upgrade Transition Audit',
    description: 'Verifies whether plain HTTP connections on port 80 are deterministically upgraded to secure HTTPS on port 443.',
    category: 'TLS / Transport Security',
    owaspMapping: 'OWASP A02:2021-Cryptographic Failures',
    cweMapping: 'CWE-319',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 3. DNS / DOMAIN INTELLIGENCE =================
  {
    id: 'cap-dns-records-observation',
    name: 'DNS Authoritative Records Observation',
    description: 'Observes published DNS records (A, AAAA, CNAME, MX, TXT, NS) for in-scope authorized hostnames.',
    category: 'DNS / Domain Intelligence',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-200',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-subdomain-enum',
    name: 'In-Scope Subdomain Relationship Mapping',
    description: 'Maps known subdomains and structural hostname hierarchy within authorized program scope rules.',
    category: 'DNS / Domain Intelligence',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-200',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-caa-dnssec-observation',
    name: 'CAA & DNSSEC Policy Presence Observation',
    description: 'Observes Certification Authority Authorization (CAA) records and DNSSEC validation presence for domain boundary protection.',
    category: 'DNS / Domain Intelligence',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-295',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-dangling-cname-indicator',
    name: 'Dangling CNAME & Cloud Pointer Indicator',
    description: 'Evaluates CNAME pointers for orphaned cloud services or unregistered third-party destination endpoints.',
    category: 'DNS / Domain Intelligence',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-284',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'RECOMMENDED',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 4. API SECURITY ASSESSMENT =================
  {
    id: 'cap-api-schema-mapping',
    name: 'API Schema & Endpoint Mapping',
    description: 'Maps API endpoints, HTTP routes, schema conventions, and parameter structures on authorized API hosts.',
    category: 'API Security Assessment',
    owaspMapping: 'OWASP A01:2021-Broken Access Control',
    cweMapping: 'CWE-1059',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'RECOMMENDED',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-graphql-introspection',
    name: 'GraphQL Introspection Availability Observation',
    description: 'Checks for enabled GraphQL schema introspection and unauthenticated __schema query accessibility.',
    category: 'API Security Assessment',
    owaspMapping: 'OWASP A01:2021-Broken Access Control',
    cweMapping: 'CWE-200',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'RECOMMENDED',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-api-error-disclosure',
    name: 'API Error & Stack Trace Disclosure Analysis',
    description: 'Analyzes API error responses (400/404/500) for verbose stack traces, internal paths, or framework leakages.',
    category: 'API Security Assessment',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-209',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-openapi-doc-exposure',
    name: 'OpenAPI / Swagger Documentation Exposure',
    description: 'Detects publicly exposed OpenAPI/Swagger specification files and interactive documentation interfaces.',
    category: 'API Security Assessment',
    owaspMapping: 'OWASP A01:2021-Broken Access Control',
    cweMapping: 'CWE-538',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 5. AUTHENTICATION & SESSION CONFIGURATION =================
  {
    id: 'cap-cookie-security-audit',
    name: 'Cookie Security Attributes Audit',
    description: 'Audits session cookies and state cookies for Secure, HttpOnly, and SameSite attribute flags.',
    category: 'Authentication & Session Configuration',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-614',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-jwt-structure-inspection',
    name: 'JWT Structure & Claims Inspection',
    description: 'Inspects JSON Web Token structures for algorithm type (none/HS256/RS256), expiration claims, and issuer claims.',
    category: 'Authentication & Session Configuration',
    owaspMapping: 'OWASP A02:2021-Cryptographic Failures',
    cweMapping: 'CWE-347',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'RECOMMENDED',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-oauth-flow-mapping',
    name: 'OAuth / OIDC Grant Flow Mapping',
    description: 'Maps authorization grant endpoints, client redirect URIs, response_type configurations, and token exchange patterns.',
    category: 'Authentication & Session Configuration',
    owaspMapping: 'OWASP A07:2021-Identification and Authentication Failures',
    cweMapping: 'CWE-287',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'SEMI_AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'REQUIRED',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'MANUAL_REVIEW_DRAFT',
  },
  {
    id: 'cap-session-timeout-indicator',
    name: 'Session Expiration & Cache Invalidation Indicator',
    description: 'Inspects session cookie max-age and cache expiration directives to verify session termination controls.',
    category: 'Authentication & Session Configuration',
    owaspMapping: 'OWASP A07:2021-Identification and Authentication Failures',
    cweMapping: 'CWE-613',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 6. TECHNOLOGY FINGERPRINTING =================
  {
    id: 'cap-tech-stack-fingerprint',
    name: 'Technology Stack Fingerprinting',
    description: 'Identifies software frameworks, web servers, backend technologies, and version metadata from response indicators.',
    category: 'Technology Fingerprinting',
    owaspMapping: 'OWASP A06:2021-Vulnerable and Outdated Components',
    cweMapping: 'CWE-1104',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-waf-detection',
    name: 'WAF & CDN Edge Detection',
    description: 'Identifies Web Application Firewalls, reverse proxies, and CDN edge infrastructure (Cloudflare, CloudFront, Akamai).',
    category: 'Technology Fingerprinting',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-693',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-framework-header-detection',
    name: 'Framework & Runtime Indicator Identification',
    description: 'Detects application frameworks and runtimes via headers (X-Powered-By, X-AspNet-Version, Server) and HTML metadata.',
    category: 'Technology Fingerprinting',
    owaspMapping: 'OWASP A06:2021-Vulnerable and Outdated Components',
    cweMapping: 'CWE-200',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 7. EXPOSURE / METADATA ANALYSIS =================
  {
    id: 'cap-sensitive-file-exposure',
    name: 'Public Metadata Manifests Exposure',
    description: 'Inspects robots.txt, sitemap.xml, and humans.txt manifests for sensitive unlisted directory references.',
    category: 'Exposure / Metadata Analysis',
    owaspMapping: 'OWASP A01:2021-Broken Access Control',
    cweMapping: 'CWE-538',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-debug-disclosure',
    name: 'Debug & Verbose Error Disclosure Detection',
    description: 'Inspects responses for debug parameters, stack traces, and verbose exception reporting modes.',
    category: 'Exposure / Metadata Analysis',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-209',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-directory-listing',
    name: 'Directory Listing & Indexing Detection',
    description: 'Detects automatic directory index listings (Apache mod_autoindex, Nginx autoindex on) exposing internal files.',
    category: 'Exposure / Metadata Analysis',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-548',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-backup-artifact-indicator',
    name: 'Backup Artifact & Archive Indicator',
    description: 'Observes standard backup file extensions (.bak, .old, .zip, ~) at specific authorized canonical endpoints.',
    category: 'Exposure / Metadata Analysis',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-530',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'RECOMMENDED',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 8. CLIENT-SIDE SECURITY =================
  {
    id: 'cap-source-map-exposure',
    name: 'JavaScript Source Map Exposure Detection',
    description: 'Checks if production frontend bundles expose live .js.map source maps revealing original application source code.',
    category: 'Client-Side Security',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-540',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-client-secrets-detection',
    name: 'Client-Side JavaScript Secret Pattern Detection',
    description: 'Analyzes client-side JavaScript assets for high-entropy tokens and API keys with mandatory secret redaction before persistence.',
    category: 'Client-Side Security',
    owaspMapping: 'OWASP A07:2021-Identification and Authentication Failures',
    cweMapping: 'CWE-798',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'RECOMMENDED',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-subresource-integrity',
    name: 'Subresource Integrity (SRI) Tag Observation',
    description: 'Verifies integrity attributes on external script and stylesheet tags to prevent CDN tampering.',
    category: 'Client-Side Security',
    owaspMapping: 'OWASP A08:2021-Software and Data Integrity Failures',
    cweMapping: 'CWE-353',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 9. CLOUD / INFRASTRUCTURE METADATA =================
  {
    id: 'cap-cloud-provider-indicator',
    name: 'Cloud Provider & Storage Domain Indicator',
    description: 'Identifies cloud provider hosting regions and object storage bucket references (S3, GCS, Azure Blob) in publicly returned content.',
    category: 'Cloud / Infrastructure Metadata',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-200',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-load-balancer-indicator',
    name: 'Reverse Proxy & Load Balancer Header Analysis',
    description: 'Analyzes Via, X-Forwarded-For, and proxy routing headers to understand edge topology without accessing internal networks.',
    category: 'Cloud / Infrastructure Metadata',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-200',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 10. CONTENT & ENDPOINT ANALYSIS =================
  {
    id: 'cap-security-txt-observation',
    name: 'RFC 9116 security.txt Policy Observation',
    description: 'Observes presence and validity of /.well-known/security.txt for authoritative vulnerability disclosure contact data.',
    category: 'Content & Endpoint Analysis',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-200',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-rate-limit-inspection',
    name: 'Rate Limiting Policy Header Inspection',
    description: 'Inspects rate limiting headers (X-RateLimit-Limit, X-RateLimit-Remaining, Retry-After) and quota enforcement behavior.',
    category: 'Content & Endpoint Analysis',
    owaspMapping: 'OWASP A04:2021-Insecure Design',
    cweMapping: 'CWE-799',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'SEMI_AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'RECOMMENDED',
    evidenceSupport: 'HTTP_PROOFS',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },

  // ================= 11. EVIDENCE & RESEARCH INTELLIGENCE =================
  {
    id: 'cap-execution-reference',
    name: 'Controlled Research Execution Reference',
    description: 'Diagnostic and integrity validation reference for the governed live research execution engine.',
    category: 'Evidence & Research Intelligence',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-693',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'NONE',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'NONE',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
  {
    id: 'cap-asset-discovery',
    name: 'Authoritative Scope Boundary Asset Discovery',
    description: 'Discovers authorized target boundaries, subdomains, and root assets defined by program policy.',
    category: 'Evidence & Research Intelligence',
    owaspMapping: 'OWASP A05:2021-Security Misconfiguration',
    cweMapping: 'CWE-200',
    implementationStatus: 'SUPPORTED',
    automationLevel: 'AUTOMATED',
    authenticationRequirement: 'OPTIONAL',
    policyRequirement: 'POLICY_CHECK_REQUIRED',
    humanValidationRequirement: 'OPTIONAL',
    evidenceSupport: 'JSON_EVIDENCE',
    reproductionSupport: 'CURL_COMMAND',
    reportingSupport: 'AUTOMATED_REPORT',
  },
];

