export const SCOPE_TYPES = {
  EXACT_DOMAIN: 'EXACT_DOMAIN',
  SUBDOMAIN: 'SUBDOMAIN',
  URL: 'URL',
  API_ENDPOINT: 'API_ENDPOINT',
} as const;

export type ScopeType = keyof typeof SCOPE_TYPES;

export const SCOPE_STATUSES = {
  IN_SCOPE: 'IN_SCOPE',
  OUT_OF_SCOPE: 'OUT_OF_SCOPE',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
  DISABLED: 'DISABLED',
} as const;

export type ScopeStatus = keyof typeof SCOPE_STATUSES;

export const POLICY_DECISIONS = {
  ALLOW: 'ALLOW',
  BLOCK: 'BLOCK',
  REVIEW_REQUIRED: 'REVIEW_REQUIRED',
} as const;

export type PolicyDecision = keyof typeof POLICY_DECISIONS;

export const PROHIBITED_OPERATIONS = [
  'DOS',
  'DDOS',
  'DENIAL_OF_SERVICE',
  'DATA_DESTRUCTION',
  'CREDENTIAL_ATTACK',
  'CREDENTIAL_STUFFING',
  'BRUTE_FORCE',
  'EXPLOITATION',
  'NETWORK_SCANNING',
  'PORT_SCANNING',
  'ARBITRARY_URL_FETCH',
  'UNAUTHORIZED_ACCESS',
  'MASS_AUTOMATION',
  'SOCIAL_ENGINEERING',
  'PHYSICAL_ATTACK',
] as const;

export const SENSITIVE_OPERATIONS = [
  'SENSITIVE_DATA_EXFILTRATION_TEST',
  'DATA_MODIFICATION',
  'PRIVILEGE_ESCALATION_TEST',
  'INTERNAL_PIVOT_TEST',
] as const;
